include ~/.cache/wal/theme-kitty.conf
font_family JetBrainsMono Nerd Font
font_size 8
window_padding_width 15
shell fish
enable_audio_bell no
confirm_os_window_close 0
allow_remote_control yes
background_opacity 1.0
dynamic_background_opacity yes
